apiVersion: v1
kind: Service
metadata:
  name: sbdemo-postgres-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
   - name: "db-port"
     protocol: "TCP"
     port: 5432
     targetPort: 5432
  selector:
    app: sbdemo-postgres-sfs
